module Calculation
end

require_relative 'calculation/gui'
require_relative 'calculation/add'
require_relative 'calculation/subtract'
require_relative 'calculation/multiply'
require_relative 'calculation/divide'
require_relative 'calculation/cancel'
require_relative 'calculation/abs'
require_relative 'calculation/neg'
require_relative 'calculation/sqr'
require_relative 'calculation/square'
require_relative 'calculation/cube'
require_relative 'calculation/cubert'
require_relative 'calculation/repeat'
require_relative 'calculation/history'
require_relative 'calculation/invalid_command'
require_relative 'calculation/parser'
require_relative 'calculation/calculator'